### ISSUE TITLE
Excluding Response Fields and Huge Performance Hits

### ISSUE THREAD

**Issue by rdegges** [jfinkels/flask-restless#168]
Hey dudes,

Love Flask-Restless, but wanted to leave an issue here as I'd love to use the library, but a showstopper in my use case (and possibly that of other people) is that Flask-Restless really has no way (currently) to properly exclude database relationship queries with the pre and postprocessor stuff.

For instance, I have an application which has several models, namely:

`State` and `Person`. Each person has a state relationship (via ForeignKey).

My API clients need to frequently grab a list of all states in the system, so they'll do something like:

GET `/api/states`

And will immediately get their screen flooded with results (because Flask-Restless is traversing the backref and generating JSON for the millions of people in each state).

Even if I were to explicitly write a postprocessor for the `GET_MANY` hook, this wouldn't really solve the problem as each request to my API endpoint `/api/states` would still result in Flask-Restless spending an enormous amount of time loading my `people` backref and eventually discarding that data and returning a response.

I think a good solution to this problem is what issue #161 is suggesting: have Flask-Restless *only* load foreign key relationships when they're explicitly eagerly loaded by Flask-SQLAlchemy.

I'm documenting this here for discussion purposes. Thank you.

**Comment by jkurtisr32** [comment]
Has this issue gotten anywhere? I loved how simple this was to set up on top of SqlAlchemy, but I really can't use it if it is bringing back a lot of extra data, as described in @rdegges OP.

I don't have a ton of experiences with APIs, but even if the overhead was not a concern, I am not sure if many MV frameworks will work out-of-the-box with data formatted in this way.

**Comment by jfinkels** [comment]
I think I'm going to implement the following. A request to `GET /api/person/1` will return something like

    {'id': 1,
     'computers': [1, 2, 3]
    }

where `[1, 2, 3]` is a list of the primary key values for each of the computers in the one-to-many relation.

This follows one of the suggestions for the [collection representation standards at jsonapi.org][1]. I'd like to implement all of the suggestions there for version 1.0.0 of Flask-Restless.

This may not be the best solution, but I'd like to at least have a start so that this library can actually be usable with large databases.

[1]: http://jsonapi.org/format/#document-structure-resource-collection-representations

**Comment by jkurtisr32** [comment]
That's a good way to do it, and would definitely solve the issue outlined in this thread.

Wouldn't it be a lot simpler to just have a link in each person object?
`computers: /api/person/1/computers`

Which would return a list of computer objects filtered by person 1. This is good for large databases because it only ever gives you the data you asked for. 

Just a thought.

**Comment by jfinkels** [comment]
On the master branch, Flask-Restless now follows the JSON API protocol. Therefore, relationships (like the `residents` to-many relationship from the `State` model to the `Person` model in the original post) are just referenced, not included unless explicitly requested by the client. This problem should be fixed.

**Comment by jasonrhaas** [comment]
So is there a good work around for this on the current stable release (0.17.0)?  I'm not ready to move to the beta version since I am using this in production and it is still under development.  Same requests as others, I would rather not have the relationship information available in my endpoint, I just want the table data.
