### ISSUE TITLE
Use SQLAlchemy Runtime Inspection API

### ISSUE THREAD

**Issue by logandk** [jfinkels/flask-restless#175]
With SQLAlchemy 0.8, a [new API](http://docs.sqlalchemy.org/en/latest/core/inspection.html) for runtime inspection is available.

There are several places where the `flask-restless` could possibly benefit from this:
* `flask_restless.views._has_field`
* `flask_restless.views._primary_key_name`
* `flask_restless.helpers.get_related_model`

**Comment by jfinkels** [comment]
Though the code has changed quite a bit since this was reported, I am currently using the inspection API in various places (although in most of our particular cases, it just returns the same object being inspected). I'm marking this as completed; please open a new issue if the inspection API needs to be used anywhere else in the code.
