### ISSUE TITLE
Eagerly load relationships when querying

### ISSUE THREAD

**Issue by taion** [jfinkels/flask-restless#405]
It looks like currently the behavior with relations is that they will be loaded as specified in the model. However, when e.g. serializing all columns, we already know that we need to eagerly load all relationships. Given that, it'd be much faster to just do the eager loading (e.g. with `joinedload`), instead of hitting the database once per relationship per object.

**Comment by dtheodor** [comment]
:+1: 

To me this looks like a crucial feature that a project like this should support. 

Defining load behavior at the model level is very limiting; it forces only a single usage pattern of your model to be performant, and at least in my applications it is never the case that I only have a single usage pattern.

Defining load behavior at the query level is really the only reasonable way to go, and it's very easy to support using the `include_columns` information that comes in from the request. It looks like [SQLAlchemy's loading techniques](http://docs.sqlalchemy.org/en/latest/orm/loading_relationships.html) is exactly the right fit for such a case.

**Comment by jfinkels** [comment]
Do you mean to apply `.options(joinedload('relationship1').joinedload('relationship2').<etc>)` to the SQLAlchemy `Query` object produced by the `search()` function in `flask_restless/search.py`? If so, I suppose this could be done at the beginning of the `DefaultSerializer.serialize_many` in the `flask_restless/serialization/serializers.py` module, since the argument `instances` is really a Query.

**Comment by taion** [comment]
Closing this for staleness. I still think this would be a good feature to have, but progress here appears to be stalled.
