### ISSUE TITLE
Overridden primary key not respected in links

### ISSUE THREAD

**Issue by kopf** [jfinkels/flask-restless#476]
On 1.0.0-dev (826c9d49c3d4a95f04c4ababd2b89f2045e59eee), when a `primary_key` is overridden for a certain API, this isn't respected by the response from a related API in the `links` section. e.g.:

`create_api(model.Tenant, primary_key='_uuid')`

```
        "tenant_user_maps": {
          "data": [],
          "links": {
            "related": "http://localhost:8888/api/v1/tenants/2/tenant_user_maps",
            "self": "http://localhost:8888/api/v1/tenants/2/relationships/tenant_user_maps"
          }
        },
```

The `/tenants/2/` in the links should really look something like `/tenants/uuid-string-here-etc/`

**Comment by jfinkels** [comment]
This can be solved in a way similar to the other "global" functions, like `url_for`, `model_for`, `serializer_for`, etc. See the `SerializerFinder` class introduced in pull request #493, for example.

The solution to this problem is to create a `PrimaryKeyFinder` class, almost identical to the others in the `helpers` module, that tracks the primary key field specified for a particular model when `APIManager.create_api()` is called. Then the links can be determined using the correct key in the `serializer` module.

**Comment by kopf** [comment]
OK great, thanks for the pointers! I've got a test written in a branch and will get going on it now.
