### ISSUE TITLE
No support for "not_any"

### ISSUE THREAD

**Issue by tahoe** [jfinkels/flask-restless#481]
I have been trying to figure out how to do a negative "any" search and couldn't find a way.
So I added one line to search.py
`
'not_any': lambda f, a, fn: ~f.any(_sub_operator(f, a, fn)),
`

and voila! it works. Any chance we can add this in? pretty dang simple update.

**Comment by tahoe** [comment]
Oh yeah, and back porting it to 0.17.0 would be awesome too...

**Comment by jfinkels** [comment]
Another solution would be to allow the client to use the `all` expression, which will appear in SQLAlchemy version 1.1: http://docs.sqlalchemy.org/en/rel_1_1/core/sqlelement.html#sqlalchemy.sql.expression.all_

But for now, I think this is a fair request, I'll work on adding it. However, I probably won't be updating version 0.17.0, since I have limited resources and there are just too many issues with it.

**Comment by jfinkels** [comment]
In pull request #520, I am adding support for the general `not` operator, which should fix this use case and more.

**Comment by jfinkels** [comment]
Fixed by pull request #520.
