### ISSUE TITLE
documentation out of date?

### ISSUE THREAD

**Issue by stgarf** [jfinkels/flask-restless#538]
Looks like the documentation is out of date with the latest flask-restless.

Is there currently a way to change accept and content-type from requiring application/vdi.api+json to anything else?

**Comment by jfinkels** [comment]
The documentation for the in-development version (currently 1.0.0b2) is at https://flask-restless.readthedocs.io/en/latest/

The documentation for the latest beta release (version 1.0.0b1) is at https://flask-restless.readthedocs.io/en/1.0.0b1/

The documentation for the latest "stable" release (version 0.17.0) is at http://flask-restless.readthedocs.io/en/stable/

As for your other question, in order to solve a multitude of design problems with Flask-Restless, we will implement the [JSON API][1] protocol in version 1.0.0, so no other content types will be accepted.

[1]: http://jsonapi.org/
